In [16]:
# 1. Create a list of 5 integers. Perform and print the result of the following operations:
# append, extend, insert, remove, pop, clear, index, count, sort, and reverse.
numbers = [10, 25, 5, 40, 25]
print("Initial list:", numbers)

numbers.append(50)
print("After append(50):", numbers)

numbers.extend([60, 70])
print("After extend([60, 70]):", numbers)

numbers.insert(2, 15)
print("After insert(2, 15):", numbers)

numbers.remove(40)
print("After remove(40):", numbers)

popped_val = numbers.pop()
print(f"After pop() [removed {popped_val}]:", numbers)

idx = numbers.index(25)
print("Index of first 25:", idx)

cnt = numbers.count(25)
print("Count of 25:", cnt)

numbers.sort()
print("After sort():", numbers)

numbers.reverse()
print("After reverse():", numbers)

numbers.clear()
print("After clear():", numbers)

Initial list: [10, 25, 5, 40, 25]
After append(50): [10, 25, 5, 40, 25, 50]
After extend([60, 70]): [10, 25, 5, 40, 25, 50, 60, 70]
After insert(2, 15): [10, 25, 15, 5, 40, 25, 50, 60, 70]
After remove(40): [10, 25, 15, 5, 25, 50, 60, 70]
After pop() [removed 70]: [10, 25, 15, 5, 25, 50, 60]
Index of first 25: 1
Count of 25: 2
After sort(): [5, 10, 15, 25, 25, 50, 60]
After reverse(): [60, 50, 25, 25, 15, 10, 5]
After clear(): []


In [18]:
# 2. Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.
students = ("Alice", "Bob", "Charlie")
try:
    students[1] = "David"
except TypeError as e:
    print("Error:", e)

Error: 'tuple' object does not support item assignment


In [19]:
# 3. Create a set of integers with some duplicate values. Print the set and explain the output.
num_set = {10, 20, 20, 30, 40, 40, 50}
print("Set output:", num_set)

Set output: {50, 20, 40, 10, 30}


In [20]:
# 4. Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.
person = {"name": "John", "age": 22, "city": "Hyderabad"}

person["age"] = 23
person["email"] = "john@example.com"

print("Final dictionary:", person)

Final dictionary: {'name': 'John', 'age': 23, 'city': 'Hyderabad', 'email': 'john@example.com'}


In [21]:
# 5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.
age = 20
if age >= 18:
    print("Eligible to vote.")
else:
    print("Not eligible to vote.")


Eligible to vote.


In [22]:
# 6. Given a 'marks' variable, print the grade: 90 and above: 'A', 75–89: 'B', 50–74: 'C', Below 50: 'Fail'
marks = 82
if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 50:
    print("Grade: C")
else:
    print("Grade: Fail")

Grade: B


In [23]:
# 7. Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.
num = 14
if num > 0:
    if num % 2 == 0:
        print("Positive and Even")
    else:
        print("Positive and Odd")
elif num == 0:
    print("Zero")
else:
    print("Negative")

Positive and Even


SECTION-B

In [24]:
import numpy as np
# 1. Create: A scalar using np.array(5), A 1D array with values 1 to 5, A 2D array (2x3) with values from 10 to 60 in steps of 10
scalar_arr = np.array(5)
print("Scalar:", scalar_arr)

arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)

arr_2d = np.array([[10, 20, 30], [40, 50, 60]])
print("2D Array:\n", arr_2d)

Scalar: 5
1D Array: [1 2 3 4 5]
2D Array:
 [[10 20 30]
 [40 50 60]]


In [25]:
# 2. Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().
random_4x4 = np.random.randint(0, 101, size=(4, 4))
print("4x4 Random Array:\n", random_4x4)

4x4 Random Array:
 [[40 30 65 46]
 [14 57 67 92]
 [72 73 69 34]
 [62 38 61  5]]


In [26]:
# 3. Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.
import pandas as pd

np_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df_from_np = pd.DataFrame(np_matrix, columns=["A", "B", "C"])
print("DataFrame from Numpy Matrix:\n", df_from_np)

DataFrame from Numpy Matrix:
    A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


SECTION-C

In [27]:
# Section C: Exploring Pandas

# 1. Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
# - Use .info(), .describe()
# - Select 'Name' and 'City' columns
# - Drop 'City' column
# - Fill any missing values in 'Salary' column with the mean
# - Remove any duplicate rows

data = {
    "Name": [
        "Alice",
        "Bob",
        "Charlie",
        "David",
        "Eve",
        "Frank",
        "Grace",
        "Hank",
        "Alice",
        "Ivy",
    ],
    "Age": [25, 30, 35, 40, 22, 28, 32, 45, 25, 29],
    "City": [
        "NY",
        "LA",
        "Chicago",
        "Houston",
        "NY",
        "LA",
        "Chicago",
        "Houston",
        "NY",
        "LA",
    ],
    "Salary": [
        70000,
        80000,
        np.nan,
        90000,
        50000,
        60000,
        np.nan,
        100000,
        70000,
        65000,
    ],
}

df = pd.DataFrame(data)

print("--- Data Info ---")
df.info()

print("\n--- Data Summary Description ---")
print(df.describe())

print("\n--- Selecting Name and City ---")
print(df[["Name", "City"]])

df_dropped_city = df.drop(columns=["City"])
print("\n--- After Dropping City Column ---")
print(df_dropped_city)

df["Salary"] = df["Salary"].fillna(df["Salary"].mean())
print("\n--- After Filling Missing Salary Values with Mean ---")
print(df)

df = df.drop_duplicates()
print("\n--- After Removing Duplicate Rows ---")
print(df)

--- Data Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

--- Data Summary Description ---
             Age         Salary
count  10.000000       8.000000
mean   31.100000   73125.000000
std     7.156194   16243.130416
min    22.000000   50000.000000
25%    25.750000   63750.000000
50%    29.500000   70000.000000
75%    34.250000   82500.000000
max    45.000000  100000.000000

--- Selecting Name and City ---
      Name     City
0    Alice       NY
1      Bob       LA
2  Charlie  Chicago
3    David  Houston
4      Eve       NY
5    Frank       LA
6    Grace  Chicago
7     Hank  Houston
8    Alice       NY
9      Ivy       LA

--- After Droppi